name: Deploy Frontend

on:
  push:
    branches:
      - bugfix/api-login

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.FRONTEND_DEPLOY_NAME }}
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  test-build:
    uses: ./.github/workflows/test-build.yml
    with:
      environment: ${{ github.ref_name }}

  docker-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test-build
    environment: DEV-ONE21
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_REPO:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_REPO:$IMAGE_TAG

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: docker-build
    environment: DEV-ONE21
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ vars.FRONTEND_DEPLOY_NAME }} \
          -f ./charts/values-dev.yaml \
            ./charts/ \
            --namespace ${{ vars.NAMESPACE }} \
            --create-namespace \
            --set image.repository=$IMAGE_REPO \
            --set image.tag=$IMAGE_TAG \
            --wait --atomic --timeout 5m
